Add integration tests and use github actions
ericclemmons/start-server-webpack-plugin pull request #35
Opened 2020-03-03 01:24 UTC by fivethreeo

2020-03-03 08:20 UTC, fivethreeo commented
Also adds support for webpack5

2020-03-03 08:58 UTC, wmertens commented
:-/ sadly, the most recent version is on the use-the-fork branch. Could you check if it works for you with  `start-server-webpack-plugin@beta`?

The mechanism changed a lot, so I'm afraid you'll need to do some adjustments to make it work on the new branch.

2020-03-03 09:05 UTC, wmertens requested changes
Can you remove the yarn dependency, and rebase this on use-the-fork? Good stuff in any case!

2020-03-03 09:05 UTC, wmertens commented on src/StartServerPlugin.js
> +      clustertOptions.inspectPort = inspectPort;
typo

2020-03-03 09:05 UTC, wmertens commented on test.sh
> +yarn run test & \
the `\` and next indentation isn't needed here, the next lines are their own command

2020-03-03 09:05 UTC, wmertens commented on .github/workflows/nodejs.yml
> +    - run: NODE_ENV=development yarn install
I'd rather limit the project to npm - it's gotten reasonably fast lately

2020-03-05 17:36 UTC, fivethreeo commented
Fixed the issues, but the travis build does not work

2020-03-05 19:14 UTC, fivethreeo commented
Working travis build now

2020-03-05 21:02 UTC, closed without merging